name: cdk-deploy

on:
  pull_request:
    branches:
      - main

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build project
      - name: Build project
        run: npm run build

      # Configure AWS credentials (from GitHub secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # CDK Bootstrap (needed only once per account/region, but safe to keep)
      - name: CDK Bootstrap
        run: npx cdk bootstrap

      # Deploy CDK Stack
      - name: Deploy CDK Stack
        run: npx cdk deploy "*" --require-approval never
